### ISSUE TITLE
Santraukos

### ISSUE THREAD

**Issue by marsav** [marsav/lii-lindat-dspace#19]
Nuo: Zita Medišauskienė
Data: 2015 m. gegužės 20 d. 09:21
Tema: Re: LII tinklalapis

Taip pat reikia, kad atskirai atsivertų santraukos, tai bus ypač aktualu angliškoje puslapio versijoje.

**Comment by marsav** [comment]
Nesuprantu reikalavimo, reikia detalių arba skečo.

**Comment by marsav** [comment]
@tkrilavicius čia vėl nesuprantu, ar kalba apie Tekstyną ar apie istorikai.lt

**Comment by tkrilavicius** [comment]
Straipsniai turi santraukas - abstract,  ir zita jų nori. Iš esmės, tai jos lyg buvo metaduomenyse, bet mes jų iš straipsnių nekarpėm ir nedėjom

**Comment by marsav** [comment]
Ir kur jos (ateity) turės "atsiverti"? Repo ar istorija.lt?

**Comment by tkrilavicius** [comment]
santrauka turėtų atsirasti kur čia http://talpykla.istorija.lt/repository/xmlui/handle/99999/29

bet čia turbūt reiktų ir išvardinti visus metaduomenis su pavadinimais

beje, o ar čia galima generuoti thumbnails, ar bent jau pdf įdėti kokį nors?

**Comment by marsav** [comment]
1) santrauka - aišku
2) metaduomenys - jie ir dabar rodomi, bet su metaduomenų identifikatoriais, paspaudus "rodyk pilną įrašą"
3) pdf nuoroda ten kaip ir padėta, kai sakai "pdf įdėti kokį nors" tai gal turi omeny "embeddint"? jei taip, tai įmanoma, bet vėl darbas, ar tikrai yra toks reikalavimas?

**Comment by tkrilavicius** [comment]
1. ok
2. a, tai matyt todėl, kad nėra, tai ir nerodo ;)
3. ne, turiu omenyje arba kažkokį thumbnail, arba kokią nors failo tipą vaizduojančią icon'ą. čia tiesiog kad istorikai geriau jaustųsi

**Comment by marsav** [comment]
![screen shot 2015-06-17 at 17 53 49](https://cloud.githubusercontent.com/assets/1196273/8210263/dffd55e4-1519-11e5-89a9-ac835c57e7cc.png)

Man rodo tuos thumbnailus

**Comment by tkrilavicius** [comment]
pdf icons kokios nors tokios
https://goo.gl/Gp8bkz

**Comment by kestas05** [comment]
Idejau pdf ikona
