### ISSUE TITLE
Nepavyksta įrašyti LII PVM mokėtojo kodo

### ISSUE THREAD

**Issue by marsav** [marsav/lii-lindat-dspace#2]
Liko neištaisytos klaidos, kurias aš Jums buvau nurodžiusi anksčiau
- vis niekaip nepavyksta įrašyti LII PVM mokėtojo kodo.

**Comment by marsav** [comment]
M: klausimas: cia kur? (gal kur ankstesniame emaile aprašyta)

**Comment by marsav** [comment]
Zita:
Instituto PVM mokėtojo kodas yra LT100001323314 Reikėtų jį įrašyti ne tik repozitoriume prie LII rekvizitų, bet ir kituose LII tinklalpio puslapiuose, kur, atrodo, irgi praleistas.

​TKR1: istorija.lt lyg visur yra, tai repo trūksta.​

**Comment by kestas05** [comment]
Įrašiau PVM kodą
