### ISSUE TITLE
Kalbos / metaduomenys

### ISSUE THREAD

**Issue by marsav** [marsav/lii-lindat-dspace#21]
Nuo: Zita Medišauskienė
Data: 2015 m. gegužės 20 d. 09:21
Tema: Re: LII tinklalapis

Dėl kalbų: išskleidus duomenis apie straipsnį, viskas anglų kalba. Tai gerai angliškoje versijoje, bet lietuviškoje turėtų viskas būti lietuviškai.

**Comment by marsav** [comment]
Jei kalba eina apie 
http://talpykla.istorija.lt/repository/xmlui/handle/99999/29?show=full

Tai ten nurodomi metaduomenų laukai-identifikatoriai, o ne "žmogiška kalba". Tai kaip kintamųjų vardai - jie paprastai neverčiami.

Galbūt paprastesnis sprendimas būtų tiesiog pašalinti metaduomenų rodymą apskritai, galimai perkeliant tik svarbiausius į dabartinį neišskleistą ("įrašo santraukos") puslapį.

Tokiu atveju šiai konkrečiai problemai skirtas #24

**Comment by marsav** [comment]
Tomai, Kęstai, gal jūs patarsit, kas toliau?

**Comment by marsav** [comment]
Galimai tai #24 dublikatas

**Comment by tkrilavicius** [comment]
Atitinka #24, bet gal reiktų galimybės matyt adminams ar pan kažkaip

**Comment by marsav** [comment]
Mataduomenų rodymas paslėptas
