### ISSUE TITLE
Leidinių atvaizdavimas: leidiniai->tomai | +naujausi tomai (numeriai ir t.t.)

### ISSUE THREAD

**Issue by marsav** [marsav/lii-lindat-dspace#25]
Zita:
Bendros pastabos: puiku, kad leidinių sąrašas pagal abėcėlę. tačiau "atidarius" leidinį reikėtų, kad pasirodytų visų jo tomų sąrašas, kurį būtų galima pildyti naujausiais tomais (numeriais ir t.t.). Šiuo metu pasirodo naujausi sukelti straipsniai, o visa kita yra per paiešką. paieška gerai, bet reikėtų ir viso leidinių tomų (numerių) sąrašo, kad lankytojas galėtų pamatyti vieno ar kito tomo visą turinį ir pasirinkti iš jo norimą straipsnį (taip, kaip yra leiidnių svetainių pirmame puslapyje su naujausiu leidinio numeriu). 
1. atidarius repozitoiumo turinio sąraše esantį leidinį (pvz.,
   Lietuvos istorijos bibliografija" turi matytis ne "Paieška", bet visas
   to leidinio numerių arba tomų sąrašas)

**Comment by marsav** [comment]
Iš dev pusės, esminis klausimas yra - kas yra įrašas, arba smulkiausias vienetas. Ar tai yra tomas (numeris), ar tai yra straipsnis tome. Taip pat klausimas, ar visada tas smulkiausias vienetas tas pats, ar gali skirtis (pvz. kartais įrašas tai straipsnis, o kartais - visas numeris viename faile).

Panašu kad dauguma atveju įrašas - tai straipsnis leidinio tome/numeryje. Tokiu atveju, collection (liet. rinkinys) būtų tik konkretus tomas/numeris (pvz. Leidinio XXX Nr. 15), o leidinys (Leidinys XXX) būtų community (liet. kolekcija).

**Comment by tkrilavicius** [comment]
Dažniausiai smulkiausias vienetas bus straipsnis. 

Tačiau tikėtina, kad pasitaikys tokių atvejų, kai bus "vienas straipsnis" visame leidinyje (yra ten keli tokie).

Aš taip spėju, kad geriausiai ir sudėlioti tokią struktūrą, bet kaip matot - patys istorikai mėtosi visą laiką, jie kol nepamato, tai nesuvokia, kaip bus (kaip ir aš kartais).

**Comment by marsav** [comment]
Zita: Į Jūsų ankstesnį klausimą atsakau: taip, leidiniai (žurnalai) turi būti suskirstyti į tomus (numerius), ir juose sudėtas visas tomo turinys. Papildomai paieška pagal autorių, prasminį žodį straipsnio pavadinime etc.

**Comment by marsav** [comment]
Artimai susijęs, beveik dublikuojantis issue: #13

**Comment by marsav** [comment]
TK: Tada mes darome visiems leidiniams bendrą struktūrą, kur hierarchija bus
1. Leidinys
2. tomas/numeris
3. straipsnis

**Comment by marsav** [comment]
Taip ir daroma
