### ISSUE TITLE
Pašalinti perteklinius redagavimo tab'us kolekcijoms ir rinkiniams

### ISSUE THREAD

**Issue by marsav** [marsav/lii-lindat-dspace#28]
Pašalinti kuravimo ir galbūt rolių skyrius?
Žr. bet kokios kolekcijos ar rinkinio redagavimą, pvz. 
http://talpykla.istorija.lt/repository/xmlui/admin/community?communityID=32

**Comment by tkrilavicius** [comment]
roles gal paliekam, jeigu jie ten norės priskirti atskirą žurnalą tik jo redaktoriams

**Comment by marsav** [comment]
Roles palikau, kitus tab'us pašalinau.
Redaguoti failai - atitinkami Java source'ai dspace-xmlui webapp'e.

Išversta daug atitinkamų tekstų:
/usr/local/dspace-5.0/webapps/xmlui/i18n/messages_lt.xml
