### ISSUE TITLE
06 17 dienos pabaiga

### ISSUE THREAD

**Issue by kestas05** [marsav/lii-lindat-dspace#32]
koregavau dspace.cfg
BUvai vel sugadines input-forms.xml - sutaisiau
koregavau items-view.xls - Metaduomenų rodymas vartotojui, pašalintas full record
koregavau message.xml, message_lt.xml - ryšium, su items-view.xls koregavomu

Reik ryt apsisprest ka daro su browse/perziura. Tomas kazkada minėjo kad tikslinga atsisakyt, užteks pilnai išplėstinės paieškos. 

Ryt tikslas susirast metaduomenų update formą ir ją sutvarkyt.

Kažkiek dar suvedžiau kolekcijų struktūros.

**Comment by marsav** [comment]
Susinchronizavau pakeitimus su source'ais ir rebuildinau. Kęstai, patikrink ar niekas nenusimušė.
