### ISSUE TITLE
Metaduomenų redagavimas

### ISSUE THREAD

**Issue by marsav** [marsav/lii-lindat-dspace#33]
Reikia:
1) sukurti naują schemą lii kuri atitinktų LII meta
2) rodyti tik tos schemos laukus metaduomenų redagavimo lauke
3) rodyti lietuviškus metaduomenų pavadinimus

**Comment by marsav** [comment]
Suprogramavau visą mechaniką, įskaitant metaduomenų pavadinimus per messages_lt.xml

**Comment by marsav** [comment]
Kęstai palieku tau išversti lii.\* meta id pavadinimus ir patikrinti ar viskas veikia kaip reikia.

**Comment by kestas05** [comment]
Martynai, vieno metadata truksta lii.lanaguage.iso

**Comment by marsav** [comment]
o sakei "qualifier neimu":)

**Comment by kestas05** [comment]
gal nesusikalbejom tiesiog

**Comment by marsav** [comment]
fxed
