### ISSUE TITLE
Neina suvedinet duomenu

### ISSUE THREAD

**Issue by kestas05** [marsav/lii-lindat-dspace#35]
Kažkas nusimušę po rebuldinimo, neduoda įvedinėt duomenų.

**Comment by marsav** [comment]
Pats dar kart rebuildinai?

**Comment by kestas05** [comment]
As nieko nedariau, tiesiog norejau duomenis vest ir ziuriu neveikia

**Comment by marsav** [comment]
Gal gali nurodyt man tikslius žingsnius, kaip reprodukuoti? Kurioj vietoj neveikia, ir kas vyksta? Meta exceptioną?

**Comment by kestas05** [comment]
Error creating Item Submission Configuration: javax.servlet.ServletException: No collection to item submission map ('submission-map') found in 'item-submission.xml'

galbut seno dspace xml uzrasytas, pabandysiu pats is backupo persirasyt, gal pasitaisys

**Comment by marsav** [comment]
Jo manau nekopinau šito į sourcus gal nežonojau kad buvo pakeistas

—

**Comment by kestas05** [comment]
Is backup atstaciau, dabar jau veikia
