### ISSUE TITLE
Rinkiniai turėtų būti rūšiuojami ne pagal title, o pagal provenance laukelį

### ISSUE THREAD

**Issue by marsav** [marsav/lii-lindat-dspace#42]

**Comment by marsav** [comment]
Atlikta, @kestas05 testuoja - Kęstai, po testavimo uždaryk šitą

**Comment by kestas05** [comment]
Kiek testavau, veikia be problemų. KOlekcija pagal title, rinkiniai pagal provenance. 
Pačiuose metaduomenyse pakeičiau provenance -> Order number. NOrint rūšiuot reikia susivest 001,002,003..... ir t.t.
