### ISSUE TITLE
dizainas

### ISSUE THREAD

**Issue by tkrilavicius** [marsav/lii-lindat-dspace#48]
## Įraše 

2015-11-19
„Kova už lietuvių kalbos teises“, arba dar kartą apie „ murzintojų“ bylą (Antisemitizmas ir jo raiška Lietuvos viešajame gyvenime 1922–1924 m.). Sirutavičius, Vladas. Lietuvos istorijos metraštis. 2010 metai, 2, 2011, lt, 51-76, talpykla.istorija.lt/handle/ja.lt/99999/1839 ﻿
## Rodyti visą ﻿

talpykla.istorija.lt/handle/ja.lt/99999/1839  turbūt nereikia, nes jis ir po nuoroda "Rodyti visą" slepiasi?

**Comment by kestas05** [comment]
Išėmiau
