### ISSUE TITLE
back to lii nuorodą padėti kur nors kitur, o padaryti nuorodą į talpykla.istorija.lt

### ISSUE THREAD

**Issue by tkrilavicius** [marsav/lii-lindat-dspace#49]

**Comment by kestas05** [comment]
Pakeičiau: Lt - pradinis puslapis, EN - Main. Nuorodą padaryt į talpyklą.istorija.lt
Taip pat patvarkyti punktai APIE ir KAIP NAUDOTIS.
Liko tik sutvarkyt kontaktus

**Comment by kestas05** [comment]
Sutvarkyta
