### ISSUE TITLE
pasirinkus bet kurį navigacijos laukelį meta klaidą

### ISSUE THREAD

**Issue by tkrilavicius** [marsav/lii-lindat-dspace#51]

**Comment by kestas05** [comment]
Klaida dėl to, kad nėra paprasčiausiai puslapių tokių. Išvis ten siūlyčiau išimt nuorodas CITUOTI, ĮKELTI, ĮRAŠO BŪSENŲ SEKA. Palikti tik DUK, APIE, PAGALBA. Arba net išvis naikint tą skiltį navigaciją.

**Comment by tkrilavicius** [comment]
Naikint
