### ISSUE TITLE
Kontaktų sąrašas

### ISSUE THREAD

**Issue by kestas05** [marsav/lii-lindat-dspace#52]
Ar pilnai viską kopijuojam iš istorija.lt? Ten pažiūrėjau, jog lt versijoje daug prirašyta kontaktų, o en tik pagrindiniai:
Adresas:Kražių g. 5, LT-01108, Vilnius
Telefonas: (+370 5) 261 44 36
Faksas: (+370 5) 261 14 33
El. paštas: istorija@istorija.lt

Gal tiek ir užteks, juo labiau Zita pati užsiminė ar jų išvis reikia,

**Comment by tkrilavicius** [comment]
Tik pagrindinius plius admin email
