### ISSUE TITLE
Patringa visas repozitoriumas

### ISSUE THREAD

**Issue by kestas05** [marsav/lii-lindat-dspace#53]
Skundžiasi karts nuo karto istorikai, kad palūžta repozitoriumas, tiesiog jo nekrauna.
Tai aš perkraunu  tomcat ir viskas atsistato.
Kažin kame kampas, kur ten galima log'us pažiūrėt??

**Comment by marsav** [comment]
Galima ieškot tomcat loguose (standartine log direktorija) arba dspace
loguose (ju vieta nurodoma dspace konfiguracijoje). Aš šiuo metu užsienyje,
neturiu galimybės pažiūrėt, grįšiu sekmadienį. Kiek mačiau kažkada su top
komanda, tai labai apkrauta operatyvinė atmintis ir didelis swap'as,
nežinau tiksliai bet galbūt ir tai įtakoja.

2015-12-02 10:01 GMT+02:00 kestas05 notifications@github.com:

**Comment by marsav** [comment]
closing as dupe of #54
