### ISSUE TITLE
Stringa repo, raso kad vietos mazai

### ISSUE THREAD

**Issue by kestas05** [marsav/lii-lindat-dspace#54]

**Comment by tkrilavicius** [comment]
ar čia nebus priloginta kalnai visko, ko nereikia?
ar ten jau hdd užkišti?

**Comment by kestas05** [comment]
MArtynas ziuri jau

**Comment by marsav** [comment]
panašu kad taip ir yra

#df
rootfs                                                  118794524 112768472
         0 100% /

root@repo:~# du -h / | grep '[0-9.]+G'
77G /var/log/postgresql
77G /var/log
77G /var
...

taigi postgress logai čia, jame prirašyta "connect: Bad file descriptor"
eilučių begalės, reiktų troubleshootint toliau kas ten yra, bet laikinai
galima juos tiesiog pratrinti

#rm /var/log/postgresql/*

nors paskui matosi kad ir duomenų sekcijos užima po kelis Gb, šiuo metu
visi jie sumoje užima 83 Gb

...
83G /mnt/data/duomenys
..

**Comment by marsav** [comment]
pasirodo kažkoks užsilikęs procesas laikė ištrintus postgreso log failus.
sutvarkyta, dabar disko užimtumas tik 18%

2015-12-07 21:43 GMT+02:00 Martynas Savickis martynas@ore.lt:

**Comment by marsav** [comment]
fixed

**Comment by kestas05** [comment]
Vel tas pats su vieta. 
As postgress loga istryniau, man idomu koki tu procesa nukilinai kad vietos atsirado
Plius, pabandziau postgresql perkraut, nu sustabde, bet nepaleidzia is naujo.
Kazkas ne taip jei vel per diena dingo visas space'as

**Comment by marsav** [comment]
Ok, patroubleshootinau, panašu kad čia trojanas kuris per postgress portą įlindo, žr. čia:
http://unix.stackexchange.com/a/248010

Taip ir buvo, kaip tame aprašyta - /tmp radau trojan kodą, o postgres funkcijose - exec111 funkciją (žr. žemiau). Pašalinau ir tuos ir tuos, bet galimybė kad trojaną vėl įstums jei nebus sustiprintas serverio saugumas, lieka. Pažiūrėsiu postgres konfigūraciją, ką ten galima padaryt. Kol kas turi veikt viskas, du down to 18%.

`
postgres-# \df+ exec111
                                                         List of functions
 Schema |  Name   | Result data type | Argument data types |  Type  | Volatility |  Owner   | Language | Source code | Description 
--------+---------+------------------+---------------------+--------+------------+----------+----------+-------------+-------------
 public | exec111 | text             |                     | normal | volatile   | postgres | c        | exec111     | 
(1 row)

postgres=# drop function exec111();
DROP FUNCTION
`

Sustiprinau Postgres konfigūraciją, kad pasiektų tik dspace useris, pagal šitą instrukciją:
http://comments.gmane.org/gmane.comp.db.dspace.user/25218

Tikėkimės, kad to pakaks. Jei problema kartosis, ieškosim kaip dar sustiprint.

Restartavau Postgres ir Tomcat, dabar veikia.

**Comment by marsav** [comment]
@kestas05 pažiūrėti kokie procesai laiko ištrintus failus, galima su šia komanda:

> lsof | grep "/var" | grep deleted

Man ten matėsi postgres userio executintos komandos "testproxy" procesas su daug threadų, kurie laikė tą ištrintą logą. Tada nukilinau pagrindinį procesą, ir logas buvo atlaisvintas (kartu ir serverio vieta).

**Comment by marsav** [comment]
fixed
