### ISSUE TITLE
"Naujausių" įrašų sekcijos rikiavimas (kolekcijos viduje)

### ISSUE THREAD

**Issue by kestas05** [marsav/lii-lindat-dspace#55]
Neina normaliai surikiuoti recently added recordų.
Padarytas papildomas metaduomenų laukas lii.order pagal kurį reikia rikiuoti.
Dspace5 viską atlieka discovery. Bandžiau redaguoti konfiguracinį failą /usr/local/dspace-5.0/config/spring/api/discovery.xml.

 
        <property name="recentSubmissionConfiguration"> 
           <bean class="org.dspace.discovery.configuration.DiscoveryRecentSubmissionsConfiguration"> 
               
                <property name="metadataSortField" value="lii.order" /> 
                <property name="type" value="text"/> 
                
                <property name="max" value="5"/> 
                 
                <property name="useAsHomePage" value="false"/> 
            </bean> 

 Pagal dc.date.accessioned rikiavo gerai pakeitus į lii.order rikiuoja neteisingai. 
Martynai gal gali užmest akį kur aš čia ką praleidau ir panašiai, kiek google'inau, tai atrodo viską padariau ko reikejo. Kaip pvz galiem imti "rezostencinė spauda->karo metų pogrindzio spauda->apzvalga". Ten yra suvestos lii.order reiksmes, pagal kurias reikia rikiuoti.

**Comment by marsav** [comment]
Išbandėm daug variantų, ir nors "default" recents konfigūracija reaguodavo į max apribojimus, arba priimdavo pvz dc.title lauką rūšiavimui, lii.order nepriimdavo.

Po įvairių bandymų panašu, kad dspace index-discovery "įjungė" lii.order metaduomenų indeksavimą. Tačiau tam kad reindeksuotųsi, prireikė iš naujo išsaugoti metaduomenis. Tą patį matyt turėtų padaryt istorikai su laukais, kuriuos jau suvedė.

Gali būt, kad tai Dspace bugas, bet svarbiausia kad radom workaround'ą.

Fix effort: 4.5h

**Comment by marsav** [comment]
Fixed

**Comment by tkrilavicius** [comment]
Sveiki,

tai istorikai patys nieko išsaugoti nemokės turbūt?

regards,
tomas krilavičius
http://ajajai.lt

2015-12-22 13:50 GMT+02:00 marsav notifications@github.com:

**Comment by marsav** [comment]
Tai nuo dabar jau jie bent šitą rūšiavimą turėtų mokėti pasidaryti. Tiesiog
jie kažką jau anksčiau buvo suvedę eilės numerius, tai kad jie suveiktų,
reikia tuos įrašus iš naujo išsaugoti (nieko kesiti nereikia, tiesiog
kitaip jų kažkodėl Dspace neindeksuoja).

2015-12-22 13:52 GMT+02:00 tkrilavicius notifications@github.com:
