### ISSUE TITLE
neveikia http://talpykla.istorija.lt/

### ISSUE THREAD

**Issue by tkrilavicius** [marsav/lii-lindat-dspace#59]
Visai neatidarė puslapio 01:59 2016-01-13
būtų gerai prikelti kuo greičiau

**Comment by kestas05** [comment]
Pataisyta. Tiesiog tomcat restartas padėjo.

**Comment by marsav** [comment]
@kestas05 kokios buvo priežastys? kiek buvo likę atminties, ką logai sakė?

**Comment by kestas05** [comment]
Nenustačiau. Atminties normaliai 94Gb laisvos, log'ų dar nežiūrėjau

**Comment by marsav** [comment]
94 Gb gal disko... be to po restartavimo jau situacija galėjo pasikeist, pvz. tomcat galėjo laikyti labai didelius failus užlockinęs. kitą kart tomcat nusėdus, dar prieš restartuojant būtų gerai surinkt tokią bazinę info (bent su 'top'  ir 'df' komandomis) ir iškart pažiūrėt paskutinius logus kokie exceptionai eina. Tada galima bus matyti ar kartojasi priežastys.

**Comment by kestas05** [comment]
Žiūrėjau prieš restartą  (galvojau vieots nelikę) ir po restarto. Atminties tiek pat buvo likę. Ok reikės kitą kart neskubėt ir pasiaiškint

**Comment by marsav** [comment]
vakar dienos dspace.log rodo:

```
2016-01-12 21:09:34,003 ERROR org.apache.solr.update.SolrIndexWriter  - Exception rolling back IndexWriter
...
Caused by: java.lang.OutOfMemoryError: Java heap space
```

T.y. kažkas leakina operatyvinę atmintį (naudojama Tomcat versijoje yra known issue leakai), arba per mažai priskirta startuojant Tomcat. Bandysiu padidinti.

**Comment by marsav** [comment]
Padidinau max mem iki 3Gb:
JAVA_OPTS="-Djava.awt.headless=true -Xms1024m -Xmx3072m -Dfile.encoding=UTF-8 -Djavax.net.debug=ssl -XX:+DisableExplicitGC"

**Comment by marsav** [comment]
> Atminties tiek pat buvo likę.

Operatyvinės atminties? Ar disko vietos?

**Comment by kestas05** [comment]
Disko. Galvojau kad vėl ta pati problema kai anakart diskas užsipildė.

**Comment by tkrilavicius** [comment]
šitą anksčiau, ar vėliau, reiks išsiaiškinti, nes ir kitame projekte gali iškilti. ar ne?
