### ISSUE TITLE
Įrašų rikiavimo eilės tvarka rinkiniuose

### ISSUE THREAD

**Issue by kestas05** [marsav/lii-lindat-dspace#61]
Katilius metaduomenyse rikiavima suvede seniausias 001, naujesnis 002 ir t.t. Sistema atvaizduoja  mažėjančiai, t..y. 003, 002, 001. Pasirodo istorikams įrašus  reikia rikiuoti nuo seniausio iki naujausio. Paprasčiausias, bet nepatogiausias būdas tai rikiavimą perrašyti: 001 naujausias, 002 senesnis ir t.t. Bet tada atsiradus naujesniam irašui, riektų kituose įrašuose pakeist reikšmes. Arba pradėt rikiavimą nuo pvz 500, 501.. kad liktų būtų galimybė įterpt 499,498, ir t.t
Kitas variantas, nieko  nekeičiant rast programinį variantą kad rikiavimas būtų asc, o n desc kaip dabar.
Bandžiau discovery.xml surast property, kuris tai aprašytų, bet neradau, o paskui jau išsiaiškinau kad nėra tokio propety, o desc yra į'hardcode'intas. Spėju pagal /opt/repository/lii/sources/dspace/dspace-api/src/main/java/org/dspace/discovery/configuration
O kad desc rūšiuoja tai manau čia nurodyta:
/opt/repository/lii/sources/dspace/dspace-cmlui/src/main/java /aspect/discovery/AbstractRecentSubmissionTransformer.java

Čia jau vėl prašau Martynai tavo pagalbos, nelabai aš ten dar įįsikertu kaip kompiliuot ir pakeist būtent tą ka reikia.

**Comment by marsav** [comment]
Įvedžiau naują config bean property - metadataSortOrder (default vertė "desc"), kuriam dabar paklūsta recentSubmissions.

discovery.xml:

```
        <!--The configuration for the recent submissions-->
        <property name="recentSubmissionConfiguration">
           <bean class="org.dspace.discovery.configuration.DiscoveryRecentSubmissionsConfiguration">
                <property name="metadataSortField" value="lii.order" />
                <property name="type" value="text"/>
                <property name="metadataSortOrder" value="asc" />
                ...
            </bean>
```

Pakeistas išeities kodas:

```
./dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/discovery/AbstractRecentSubmissionTransformer.java
./dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoveryRecentSubmissionsConfiguration.java
./dspace-api/src/main/java/org/dspace/discovery/DiscoverQuery.java
```

**Comment by marsav** [comment]
fixed

**Comment by kestas05** [comment]
Iškilo dar problema:

Istorikai prašo:
Reikia sutvarkyti rikiavimą laikraštėlių kur daugiau 20 numerių. Karo meto spauda laikraštėliai: Į laisvę, Lietuvių fronto biuletenis, Nepriklausoma Lietuva, Karo metų atsišaukimai ir kiti spaudiniai. Pokario partizanų laikraštėlį Laisvės balsas.

Ten recent submission rikiuoja kaip priklauso "asc", bet kadangi rinkinyje daugiau negu 20 įrašų, tai norint matyt daugiau jų, reikia spaust "view more", tada atsiranda puslapiavimas 1-20, 21-40, ir t.t. Bet problema kad čia nusimuša rikiavimas, viskas rikiuojasi atvirkščiai, t.y. "desc"

Problemos sprendimą matau arba vėl kodą nagrinėt kas kaip, arba padaryt kad puslapiuotu kaip pvz ne 20 o kokia 100, ir tada problemos kaip ir nėr.

**Comment by tkrilavicius** [comment]
šiuo atveju turbūt užtektų paprastesnio ilgo puslapiavimo, nors tada, aišku, problema išlįs, jeigu norės sudėti 10 metų kokius nors leidinius

**Comment by kestas05** [comment]
100 padariau. Pakaks pradžiai
