### ISSUE TITLE
paieška per visus laukus rezistencinės spaudos dalyje

### ISSUE THREAD

**Issue by tkrilavicius** [marsav/lii-lindat-dspace#65]
būtų gerai padaryti, kad veiktų paieška ir per pastabų ir kitus laukus, kiek suprantu, rezistencinėje spaudoje neveikia

**Comment by marsav** [comment]
gal galima konkrečiau, kuriuose konkrečiai laukuose?
komentarų lauką jau pridedu

**Comment by marsav** [comment]
beje, nėra galimybės paiešką "tuninti" pagal susigalvotą skyrių, ji yra bendra visai sistemai. t.y. ji vienodai veiks tiek Rezistencinės spaudos, tiek kitose kolekcijose/rinkiniuose.

**Comment by tkrilavicius** [comment]
per visus laukus, kiek yra, tegu ir ieško, ir visos sistemoj gerai, kad
taip ieškotų

regards,
tomas krilavičius
http://ajajai.lt

2016-02-22 10:47 GMT+02:00 Martynas S. notifications@github.com:

**Comment by marsav** [comment]
Aš matau tik šiuos laukus, kuriuose logiška ieškoti:

jau pridėta:
- dc.title
- lii.keyword
- lii.comment
- dc.contributor

dar tuoj pridėsiu:
- lii.publication

kituose laukuose (lii.tome, lii.pages, lii.date.issued, lii.ident) nematau prasmės ieškoti, nes ten bus skaičiai, arba jie išvis nenaudojami (lii.ident?)

pataisykit jei klystu

**Comment by marsav** [comment]
Dabar ieškoma per visus aukščiau nurodytus laukus. 
Galima testuoti pvz. ieškant šių terminų:
"Hakenkreuzas", "rotatoriumi"
